---
name: Build & maybe upload PyPI package

on:
  push:
    branches: ["main"]
    tags: ["*"]
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  build-package:
    uses: ./.github/workflows/build-and-check-python-package.yml

  debug:  
    runs-on: ubuntu-latest
    steps:
    - name: Dump vars context
      env:
        VARS_JSON: ${{ toJSON(vars) }}
      run: echo "${VARS_JSON}"

  # Upload to Test PyPI on every commit on main
  release-test-pypi:
    name: Publish dev package to test.pypi.org
    environment: release-test-pypi
    if: github.repository_owner == 'epam' && github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build-package

    steps:
      - name: Download packages built by build-and-inspect-python-package
        uses: actions/download-artifact@v4
        with:
          name: Packages
          path: dist

  # Upload to PyPI on every GitHub Release
  release-pypi:
    name: Publish released package to pypi.org
    environment: release-pypi
    if: github.repository_owner == 'epam' && github.event.action == 'published'
    runs-on: ubuntu-latest
    needs: build-package

    steps:
      - name: Download packages built by build-and-inspect-python-package
        uses: actions/download-artifact@v4
        with:
          name: Packages
          path: dist
